# Generated by Django 3.2.7 on 2022-10-31 22:29

from django.db import migrations, models
import ofa.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(blank=True, default=ofa.utils.media.default_profile_image, null=True, upload_to=ofa.utils.media.cover_image_upload_path, verbose_name='Cover Picture'),
        ),
    ]
