# Generated by Django 3.2.7 on 2022-11-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_cover_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
