# Generated by Django 3.2.7 on 2022-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_verified_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50),
        ),
    ]
