# Generated by Django 3.2.7 on 2022-11-01 15:42

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='workplace',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=auto_prefetch.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='user',
            field=auto_prefetch.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
            preserve_default=False,
        ),
    ]
