# Generated by Django 3.2.7 on 2022-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221101_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university_logo',
            field=models.URLField(blank=True, help_text='Provide an image address to the company logo'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='company_logo',
            field=models.URLField(blank=True, help_text='Provide an image address to the company logo'),
        ),
    ]
