# Generated by Django 3.2.7 on 2022-11-16 15:20

from django.db import migrations, models
import ofa.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221101_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[ofa.utils.validators.validate_age]),
        ),
    ]
