# Generated by Django 3.2.7 on 2022-11-16 20:24

from django.db import migrations, models
import ofa.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=ofa.utils.media.image_upload_path, verbose_name='Profile Picture'),
        ),
    ]
